[build]
  command = "npm ci && npm run build"
  publish = "dist"  # Adjust according to your actual build folder
  
[build.environment]
  SHELL = "/bin/bash"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200



